### ISSUE TITLE
Lynx logo

### ISSUE THREAD

**Issue by getlynx** [clockuniverse/xplorenow#14]
I posted a DM with the latest new Lynx logo for the site. PNG and SVG options are available.

**Comment by clockuniverse** [comment]
Once I get the online version I will close this ticket.

**Comment by clockuniverse** [comment]
Got the new logo link, but it looks like xplorenow has a logo size bug so once that is fixed I will add to the production site.
https://getlynx.io/wp-content/uploads/2020/07/LYNX_3COLOR_CMYK.png
