### ISSUE TITLE
Whitepaper as Quality item?

### ISSUE THREAD

**Issue by coldcity** [clockuniverse/xplorenow#4]
Presence of a whitepaper could count towards Quality points.

**Comment by clockuniverse** [comment]
I think this is a great idea.  Added to the site.

If you reply to this with a link to your white paper I will add it.

**Comment by coldcity** [comment]
Wonderful, thanks :)

Coin-launch whitepaper - https://litecoinca.sh/downloads/launch_whitepaper.pdf
The Hive : Agent-based mining on Litecoin Cash - https://litecoinca.sh/downloads/hive_whitepaper.pdf
The Hive: Optimising Chainwork Scaling - https://litecoinca.sh/downloads/hive_whitepaper-enhancements_optimising_chainwork_scaling.pdf
OPUS 12 Global and LCC : Position Paper - https://litecoinca.sh/downloads/ACAIM_position_paper.pdf

(I'm not sure it makes sense to credit multiple papers with multiple Quality points rather than a "yes there's a whitepaper / no there isn't", but of course at your discretion!)

**Comment by clockuniverse** [comment]
I added your coin launch whitepaper.  If you prefer  a different whitepaper I can swap it out.

I haven't decided on how to deal with multiple links like that yet.  I also added a secondary multiwallet recently and kind of feel like it is a similar thing.  I have to think about it some more!
